[package]
name = "ne-g3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#tokio = { version = "1.18.0", features = ["full"] }
serialport = "4.1.0"
#tokio-util = {version = "0.7", features = ["codec"]}
#tokio-serial = "5.4.1"
#mio-serial = "5.0.1"
bytes = "1"
cfg-if = "1"
#futures = "0.3"
log = "0.4.3"
env_logger = "0.9"
num_enum = "0.5.7"
# crossbeam = "0.8.1"
# crossbeam-channel = "0.5.4"
flume = "0.10.12"
clap = "3.1.18"
thiserror="1.0.31"
lazy_static = "1.4.0"